vim.notify = require("notify")

require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.tagbar")
require("core.plugin_config.toggleterm")
-- require("core.plugin_config.completions")
-- require("core.plugin_config.autopairs")
require("core.plugin_config.oil")
require("core.plugin_config.leap")
-- require("core.plugin_config.telescope")
require("core.plugin_config.fzf")
require("core.plugin_config.vs-tasks")
require("core.plugin_config.buffer-manager")
require("core.plugin_config.nvim-early-retirement")
require("core.plugin_config.nvim-notify")
require("core.plugin_config.formatting")
require("core.plugin_config.linting")

vim.notify("All plugins loaded succesfully", "info")
